[package]
name = "chip8"
version = "0.1.0"
authors = ["laurst"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
quicksilver = "0.4.0-alpha0.5"
rodio = "0.11.0"
